### ISSUE TITLE
Display the 'Updated' date on package details page

### ISSUE THREAD

**Issue by LottePitcher** [umbraco/Umbraco.Packages#106]
On Our you can search packages and sort by 'updated'.

On the package details page there is no obvious 'updated' date.  There are upload dates in the file listing, but the package information section has the 'created' date only:

![image](https://user-images.githubusercontent.com/4716542/99543166-c74fb180-29aa-11eb-9e88-2f311227633d.png)

When evaluating packages, I believe it's important to know how active the package is, so displaying a 'updated' date in the information section would make this easier.

Would need to understand what logic is behind the 'updated' sort on the packages and display the date that's used in the sort.

**Comment by ronaldbarendse** [comment]
The Marketplace now shows the updated date (next to the listed on Marketplace date) 👍🏻
