### ISSUE TITLE
Package results list will have layout issues with 8.10.0 and 1m downloads

### ISSUE THREAD

**Issue by LottePitcher** [umbraco/Umbraco.Packages#107]
When uSync hits a million downloads (it's not _that_ far off...) and 8.10.0 is out, looks like we'll have layout issues, as per this mock up:

![image](https://user-images.githubusercontent.com/4716542/99650613-89f03000-2a4d-11eb-964a-fb6f14ec83d5.png)

Maybe in this listing page the download number could display as 100K, 1m, 1.1m etc rather than full number?  Full number is on the package details page.

**Comment by jmayntzhusen** [comment]
We made it just in time! https://github.com/umbraco/OurUmbraco/pull/664 has been merged and deployed today!
