### ISSUE TITLE
Package Tools: UmbPack

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco.Packages#14]
Command-Line tool to create Umbraco Zip based packages, _(work as an addition/alternative to the MsBuild / AppVayor methods?)_

Much like the NuGet Pack command, which tasks a [nuspec file](https://docs.microsoft.com/en-us/nuget/reference/nuspec) and generates a NuGet Package, I have the start of something similar which could us a package.xml file - and generate a Umbraco .zip file. 

eg. 
```
UmbPack myPackage.zip -version 1.2.0 
```

Would generate version 1.2.0 of the package based on the file.

most of it would be as now, maybe with wildcard/glub support in the package file - [Nuget Reference 
](https://docs.microsoft.com/en-us/nuget/reference/nuspec#including-content-files)

e.g. 
```
 <file path="../MyPackage/Bin/Release/myPackage.*.dll" orgPath="~/bin" />
 <file path="../MyPackage/App_Plugins/MyPackage/*" orgPath="~/App_Plugins/MyPackage" />
```

**Comment by bielu** [comment]
@KevinJump I think it will be redundant as:
https://github.com/umbraco/Umbraco.Packages/issues/19

**Comment by KevinJump** [comment]
yes, might make sense to add this as an extra command line parameter to warren's Umbraco package tool where we could create a basic package.xml from a nuspec file. at least as a helper. 
#30

**Comment by jmayntzhusen** [comment]
Closing in favor of https://github.com/umbraco/Umbraco.Packages/projects/2
