### ISSUE TITLE
Package Migrations - installing data from a package

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco.Packages#21]
The term "Package Migrations" is just a title i made up several years ago. The idea is:

* Streamline the behavior between Nuget packages and Umbraco packages for installing data
* Allow for Umbraco data to be installed via Nuget packages

There's a short writeup about this here:  https://github.com/umbraco/Umbraco.Packages/issues/15#issuecomment-550085961 which I've copied (and updated) here:

* makes both nuget packages and umbraco packages work as one (i.e. you will be able to install data with nuget packages in the exact same way as if an umbraco package was installed in the back office)
* developers don't have to do any dirty hacks on startup to run custom migrations, this will all be taken care of appropriately and to avoid any startup costs
* when a package migration is detected (i.e. a new package has been installed or a package has been updated where the new version has migrations), the Umbraco installer will execute, but under a different type of runtime state with a different UI showing which packages require migrations to run, then the user clicks 'upgrade' (or whatever) and the installer will run just like normal. This way we get feedback about any errors that might be occuring. 
  * It would be possible to have an option to run these silently but IMO that is not a good experience since if any errors happen then "kaboom" and the user has no idea what went wrong...  so what needs to happen is that we have a silent option and if errors do occur we stop the app execution and render a nice error screen stating what went wrong (in fact we should have this option for the normal installer for patch upgrades ;) ) 
  * Another option that should exist is that there should be a configured 'holding page' that is displayed to any public user visiting the site if the site is in an upgrade/install/migration state and only the logged in administrator actually gets redirected to the umbraco install screen
* this would obsolete the existing "package actions" xml format that requires custom xml providers/types

There's some discussion about that here https://github.com/umbraco/Umbraco.Packages/issues/19 so wanted to move that discussion here purely about:

* Allow data to be installed by packages, nuget and the back office
* Hopefully streamline the way that data is installed by either package format: nuget or umbraco packages
* The current "package action" format is not very friendly since it requires manually writing XML and it doesn't track what has been run and not run or dealing with upgrades whereas the current umbraco Migrations does all of this

Current work arounds that package developers currently do for Nuget based packages are:

* Run custom migrations manually and in various ways that are not fully supported by Umbraco, potentially slowing down startup and not being able to report errors visually
* Install custom dashboards that require the developer who installed the package to manually execute actions on the dashboard to install the package data - this is also then required to be done on each environment

Would love to know if there are other ideas on how to make data installation and upgrades work nicely for both package formats.

**Comment by jmayntzhusen** [comment]
Also some good discussion in this old PR: https://github.com/umbraco/Umbraco-CMS/pull/1319

**Comment by martindotcontrol** [comment]
I'm currently using this https://github.com/Shazwazza/Articulate/blob/1b735583a04850eaf0c204aebe88e433fbef1286/src/Articulate/Packaging/ArticulateDataInstaller.cs#L92 exact approach in combination with the migrations. This way you can at least reuse the generated manifest. 

Although probably not desired but it would already help if there was (limited) access to the packaging services so you don't need to resort to reflection?

**Comment by Shazwazza** [comment]
@martindotcontrol interesting you found that tidbit of code :) Ideally in the future allowing all of this stuff as a first class citizen of packages would be ideal. If you install a package via nuget it should show up in the back office as being installed automatically, just as if you installed it in the back office. Articulate - as you have seen - jumps through a LOT of hoops to make that happen and it's certainly not pretty.  Of course some of this could be publicized in the core - that's pretty easy (feel free to send a PR) but it still requires a lot of manual work to make that happen, it's not a seamless experience.

**Comment by jmayntzhusen** [comment]
Closing this issue for now. We have an RFC running that involves this, once that is through the process we will open new tasks and issues based on the decisions in the RFC.

https://github.com/umbraco/rfcs/pull/22
