### ISSUE TITLE
Article: How to create a NuGet package

### ISSUE THREAD

**Issue by jmayntzhusen** [umbraco/Umbraco.Packages#4]
Step by step guide on making a NuGet package out of your package. Should be similar to https://our.umbraco.com/documentation/Extending/Packages/Creating-a-Package/ but highlight some of the changes when it comes to NuGet.

**Comment by KevinJump** [comment]
i'll take a stab at this one.

**Comment by KevinJump** [comment]
Docs PR: https://github.com/umbraco/UmbracoDocs/pull/2112
