### ISSUE TITLE
Ability to delete a draft package

### ISSUE THREAD

**Issue by LottePitcher** [umbraco/Umbraco.Packages#42]
# Feature request

Now that people can see their 'draft' packages on Our, we should allow people to delete them.

## Type of feature

Our feature

## Detailed description

Since the change that enabled draft packages to be visible to the package owners to Our went live, I know at least one package developer who has a really old draft package now appearing in their list, and they want to delete it!

Once a package has been put live it makes sense that you can't then delete it (you would 'retire' it instead).  However if a package has never been put live, I suggest there is no reason why we shouldn't allow package developers to delete it.

**Comment by ronaldbarendse** [comment]
We won't implement this feature for Our anymore, now it's replaced by the Marketplace. Please reach out to HQ if a draft version needs to be deleted though!
