### ISSUE TITLE
Packages: hide Umbraco versions in "Package Compatibility" that are below the lowest required version

### ISSUE THREAD

**Issue by abjerner** [umbraco/Umbraco.Packages#48]
For my redirects package, I've specifically set the minimum required version to 8.1, but older Umbraco versions are still shown in the **Package Compatibility** section to the right.

Proposal: don't show Umbraco versions below the minimum required version.

I think it's still fine to show newer versions than what I have marked as supported. For instance, the newest version I have marked as supported is currently 8.5, but I'd imagine it works without any changes in 8.6 once out. But on the other hand, it probably won't work when jumping to the next major. 

![image](https://user-images.githubusercontent.com/3634580/75234940-c1ca8f80-57bb-11ea-904c-25b169534705.png)

**Comment by abjerner** [comment]
@jmayntzhusen good point 👍 

It just feels a bit wrong for a new package.

Anyways, as someone has suggested before, I think the **Package Compatibility** section could do with an overhaul. Eg. because:

- compatibility is reported on the overall package, and not specific releases
- no feedback when users submit their reports (package could work fine, but used wrong)
- not possible to follow up with users submitting reports

But I'd imagine this is a task for another day 🤔

**Comment by jmayntzhusen** [comment]
Hey @abjerner 

We have started looking into Our improvements. I have added this issue to our project board as "Needs scoping". 
We will take a look at this issue on our next package team meeting and discuss what we want to do about this, then likely split it into more concrete issues.
