### ISSUE TITLE
[Q]: How is popularity calculated and is it the right metric?

### ISSUE THREAD

**Issue by DanDiplo** [umbraco/Umbraco.Packages#49]
This is less of a request and more of a query (so I apologise for breaking the template) ... 

Currently the default view for packages is to view them ordered by popularity. But how is popularity calculated? I can see a few metrics that can be used, such as download count and "hearts", and presume there might be some weighting down to time period (ie. more recent downloads count more) but can't see any discernible logic in why certain packages appear first? For instance, Contour appears right at the top of the results, yet this is a package for Umbraco 6 that has been obsolete for years... It would be good to have transparency on this.

Secondly, is popularity the best way of presenting packages to people who might be new to Umbraco whilst also catering to veterans? Whilst it seems like an obvious measure of how "good"  a package is, is it likely to create a feedback loop where the packages shown first are downloaded the most and then in turn become more popular? Does this limit visibility to packages that might be very useful but are more niche or just can't surface because of this loop? 

I wonder whether a more curated approach might be better? Obviously this would be more subjective, but as we have a package team then could they not be trusted to "feature" packages, perhaps on rotation? Maybe adding a review or overview of the package? Obviously, there could be conflicts of interest (Hi Kevin!) but I'm sure that could be worked around.

I guess it would be interesting to discuss this since the packages page is often a first-impression of Umbraco. Is it the best it can be?

**Comment by KevinJump** [comment]
Hi Dan, 

It's super magic ❇️ a bit of a black art and performed in the Examine Indexer! for more info : https://github.com/umbraco/OurUmbraco/blob/master/OurUmbraco/Our/Examine/ProjectPopularityPoints.cs#L129

We haven't touched this for the latest update - so at the moment its a combination of downloads in the last 6 / 12 months , votes ❤️ , Having source code link, working on cloud and having a forum. all weighted differently. 

I can't speak for Umbraco on having a curated list - I can see it would have merit, but its a bit of a minefield for us as you say with potential conflicts etc... so for the latest update we played it safe and didn't what lists where already shown

There are also a couple of issues around for adding things like ratings to packages, which might make for a more 'sensible' scoring and there are some rouge packages that are old, not current but still seem to score highly so and resolving that this is something that i know @dawoe has been looking into.

**Comment by dawoe** [comment]
Hi @KevinJump and @DanDiplo 

I'm actually looking into this as we speak. For example you webshop is up there as well pretty high. The package doesn't even have a current release. But still receives about 4 downloads per day. 

@jmayntzhusen looked in to Google Analytics and these downloads are not happening on our through a browser. So either this is getting installed that many times through the backoffice, which seems odd to me.

Only other viable causes are 
- Somebody has set up some kind of automated downloads on our
- Or the download links are followed by search engine crawlers

Dave

**Comment by dawoe** [comment]
I created a PR that will block crawlers from following package download links : https://github.com/umbraco/OurUmbraco/pull/555

Let's see if this has effect.

Dave

**Comment by ronaldbarendse** [comment]
The problems outlined in this issue were taken into account when developing the [Marketplace](https://marketplace.umbraco.com/) (that replaced the Our Packages section) and the 'most popular' overview now uses the CMS package telemetry data of the last 2 weeks to calculate popularity.

If you want to continue this discussion, please create a new issue on the [Marketplace issue tracker](https://github.com/umbraco/Umbraco.Marketplace.Issues/issues).
