### ISSUE TITLE
[Q]: How to get "Works on Umbraco Cloud" enabled?

### ISSUE THREAD

**Issue by leekelleher** [umbraco/Umbraco.Packages#50]
# Request for collaborators

## What help am I looking for

Following on from reading #49 about how the popular packages are weighted, I wasn't aware that "Works on Umbraco Cloud" was a factor.  So I'd like to tick that box for a few of my v7 packages, (if that's still applicable?)

[According to the documentation](https://our.umbraco.com/documentation/Umbraco-Cloud/Frequently-Asked-Questions/#do-you-support-package-x-on-umbraco-cloud), currently the only way is to reach out to Umbraco Cloud support via portal chat.

![Annotation 2020-02-26 104343](https://user-images.githubusercontent.com/209066/75337425-e474ab00-5884-11ea-94c7-b030a682cdfd.png)

That feels a little disjointed - but then I don't know what the internal workflows are within Umbraco HQ.  I feel happier requesting via the Packages Team.

## Package info

The following packages have [ValueConnectors in the Umbraco.Deploy.Contrib library](https://github.com/umbraco/Umbraco.Deploy.Contrib/tree/dev/src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors), (for Deploy v2 at least), and work on Umbraco Cloud v7 projects. _(In fact, they were specifically developed on Umbraco Cloud projects. 🎉)_

Name: **Nested Content**
Link to repo: https://our.umbraco.com/packages/backoffice-extensions/nested-content/

Name: **Doc Type Grid Editor**
Link to repo: https://our.umbraco.com/packages/backoffice-extensions/doc-type-grid-editor/

Name: **Stacked Content**
Link to repo: https://our.umbraco.com/packages/backoffice-extensions/stacked-content/

Name: **Content List**
Link to repo: https://our.umbraco.com/packages/backoffice-extensions/content-list/

Name: **Property List**
Link to repo: https://our.umbraco.com/packages/backoffice-extensions/property-list/

**Comment by dawoe** [comment]
Hi @leekelleher 

There should at least be a option to trigger the request for review if it works on cloud from the package edit page.

I only have one package listed as works on Cloud, while all my packages do.

Especially if you filter on packages that work on Umbraco Cloud : https://our.umbraco.com/packages/?category=uaas

Only a few packages get listed. For a newcomer to Umbraco this would indicate that I can't  use many packages on cloud.

Dave

**Comment by jmayntzhusen** [comment]
Yea think we should have a specific issue about how we should deal with this going forward, what the review process to be determined "cloud compatible" is, etc. There is a big difference between being able to install a package on Cloud and having gone the extra mile to think in the deployment flow, valueconnectors, etc.

Another potential issue is what about packages that may work on v7 sites but not v8 sites?
Fx. Property editors that will require a valueconnector may be compatible in their v7 version but not their v8 version yet?

**Comment by jmayntzhusen** [comment]
Thanks @leekelleher 

I have made a seperate issue detailing the functionality we would want to have for users to request a Cloud review here: https://github.com/umbraco/Umbraco.Packages/issues/53

I have also flagged the packages you listed for now, and will close this issue 🙂
