### ISSUE TITLE
Allow updating of package file versions without uploading a new file

### ISSUE THREAD

**Issue by LottePitcher** [umbraco/Umbraco.Packages#54]
# Feature request

If you want to update the versions that your current file supports you have to re-upload the same file and then set the versions as required during that process (oh and then archive the previous one and set this new one as 'current').  Could we add the ability to edit the information that you set for a file without having to upload a new one?

## Type of feature

Our feature

## Detailed description

When uploading a new file, you are asked to complete:

![image](https://user-images.githubusercontent.com/4716542/75977236-db628a00-5ed3-11ea-8952-783eb0885cba.png)

Could we allow users to edit this information for existing files?

Perhaps not the 'filetype' or supported .net runtime questions.  If either of those were changing a new file would need to be uploaded I believe.

I hope this would mean that we would end up with more reliable information from the package maintainers themselves about what versions their packages have been tested on.

**Comment by jmayntzhusen** [comment]
Depends on #68
