### ISSUE TITLE
Packages with many versions break the table layout

### ISSUE THREAD

**Issue by LottePitcher** [umbraco/Umbraco.Packages#55]
# Issue (Our)

Because there are no spaces in the list of supported versions, files with many supported versions cause the table to expand and so the button disappears off to the right (no horizontal scrollbar appears).  I suggest the simplest solution to this would be to insert a space after each delimiting comma – then the content would wrap onto a new line instead of causing the table to expand.

![image](https://user-images.githubusercontent.com/4716542/75977607-ad317a00-5ed4-11ea-9efb-5db244ba6640.png)

**Comment by jmayntzhusen** [comment]
Shouldn't be too hard to do something like v790-v7150 fx.. But I think this may need a larger overhaul.

Would also love to get rid of the weird `vxxx` syntax 😁

**Comment by crgrieve** [comment]
updated in PR: https://github.com/umbraco/OurUmbraco/pull/565

**Comment by jmayntzhusen** [comment]
Thanks for the PR! It has now been deployed to Our as well 🎉
