### ISSUE TITLE
Packages Profile List – make it easier for people to see their actively maintained packages

### ISSUE THREAD

**Issue by LottePitcher** [umbraco/Umbraco.Packages#56]
# Feature request

If someone has many packages, especially some old ones, then it really isn’t very easy for them to easily maintain their currently active ones.  

## Type of feature

Our feature

## Detailed description

For example in this screen shot below, the second package is ‘retired’ but you can't tell that, and all the packages listed at the top are really old as the order appears to be alphabetical. This user does have some current packages but they are somewhere down the bottom after all their old ones!

![image](https://user-images.githubusercontent.com/4716542/75977872-33e65700-5ed5-11ea-990b-52f70028c8e4.png)

Suggestion:

Rather than adding a visual indicator that the package has been retired, why not split this into two lists, “Active Packages” then “Retired Packages”.  Having the heading “Active Packages” might encourage package developers to retire ones that need it.

**Comment by jmayntzhusen** [comment]
Closed via https://github.com/umbraco/OurUmbraco/pull/563
