### ISSUE TITLE
Improve UI around making a package live

### ISSUE THREAD

**Issue by LottePitcher** [umbraco/Umbraco.Packages#57]
# Feature request

When you make a package live the screen just refreshes, there is no indication that this has actually worked.

## Type of feature

Our feature

## Detailed description

![image](https://user-images.githubusercontent.com/4716542/75978131-c4bd3280-5ed5-11ea-94e8-61eaeffc8164.png)

Could the screen confirm that the package has gone live and then display its public URL?

I didn’t actually realise you could ‘unlive’ a package, thought you had to retire it.  This screen could be more helpful if had two different 'views'.  One for a draft package, such as it is now (without checkbox ticked) and then a second view which had a ‘Remove package’ button that did the equivalent of the untick and Save. It would be helpful if this second ‘live’ view had a link to the public URL of the package so the user can easily check how it looks after making any changes.

**Comment by jmayntzhusen** [comment]
Depends on #68
