### ISSUE TITLE
Remove the 'make current' button from the screenshots listing

### ISSUE THREAD

**Issue by LottePitcher** [umbraco/Umbraco.Packages#58]
# Feature request

As far as I can tell making a screenshot ‘current’ has no effect on the order that the images appear in, in fact has no effect anywhere. Making a screenshot 'current' does, however, mean that if you don’t go back and re-select the package file as ‘current’ then your package page will be showing as ‘no current release’.

## Type of feature

Our feature

## Detailed description

If ‘make current’ does indeed serve no purpose for screenshots, can we hide that column so we don't have to tell people to go back and make sure that the package file is current?

![image](https://user-images.githubusercontent.com/4716542/75978377-4319d480-5ed6-11ea-89e5-2db2ea29ab05.png)

**Comment by jmayntzhusen** [comment]
Depends on #68
