### ISSUE TITLE
'No current release' message looks like a button

### ISSUE THREAD

**Issue by LottePitcher** [umbraco/Umbraco.Packages#59]
# Feature request

Confusing UI as there isn't anything to download if there is no current version

## Type of feature

Our feature

## Detailed description

![image](https://user-images.githubusercontent.com/4716542/75978610-cf2bfc00-5ed6-11ea-9d79-3f79dd0f4686.png)

It looks like a button, and the cursor changes to a hand on hover.  It would be more obvious that there wasn't a current download, if this wasn't a 'button'?

**Comment by jmayntzhusen** [comment]
Depends on #68 - how about we just make it so you need to have a valid current release and leave the button as is? 😁
