### ISSUE TITLE
[FR]: Contact Package devs if there are breaking changes in new releases

### ISSUE THREAD

**Issue by TimGeyssens** [umbraco/Umbraco.Packages#62]
Sounds like a nice and friendly gesture to contact package devs so they are aware of upcoming changes and can take action before the final (breaking release is out)

**Comment by jmayntzhusen** [comment]
Hey Tim,

This is something we try to do, but I realize that we didn't catch on to the breaking changes in the 8.6 release, definitely some room for improvement 🙂

Will include a mention of the 3 breaking changes for 8.6 in the next newsletter coming next week, but in the future we will aim to have such a mention out to people before the actual release of a breaking change!

**Comment by TimGeyssens** [comment]
Sweet
