### ISSUE TITLE
Add a more prominent link to My Packages

### ISSUE THREAD

**Issue by LottePitcher** [umbraco/Umbraco.Packages#65]
# Feature request

When you've logged in to Our and you click top right on your avatar a pop up menu appears.  You then have to click 'edit profile' in the top right, and then 'packages' in the side menu of the next page.  I always forget you have to click the 'edit profile' link to start the journey to your own packages!

Step 1:
![image](https://user-images.githubusercontent.com/4716542/79011556-35eaa800-7b5c-11ea-889d-01d7d2930c19.png)

Step 2:
![image](https://user-images.githubusercontent.com/4716542/79011605-4569f100-7b5c-11ea-8514-a8b769e7208e.png)

Packages aren't actually 'part' of your profile, they're managed separately as you can see from the link above.  So is there any reason why we couldn't put a 'My packages' link under the 'View my public profile' link so it's more obvious ... like this?

![image](https://user-images.githubusercontent.com/4716542/79017438-3e95ab00-7b69-11ea-90bc-938390f4f8b6.png)

Perhaps 'Manage my packages' would be better wording?

**Comment by AaronSadlerUK** [comment]
Just submitted a pull request :D

https://github.com/umbraco/OurUmbraco/pull/634

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/OurUmbraco/pull/634
