### ISSUE TITLE
Package Search Pagination gives `next` button even if there are no more pages

### ISSUE THREAD

**Issue by DanDiplo** [umbraco/Umbraco.Packages#66]
I noticed that the "next" link in the package search pagination appears even when there are no more packages to be shown. eg.

https://our.umbraco.com/packages/?page=4&orderBy=popularity&q=&version=8&category=

Click "Next" and you are into empty territory and can just keep going...

![image](https://user-images.githubusercontent.com/6676168/80125883-30448780-858a-11ea-9095-513984b16c3a.png)

You can also get an error page by manually changing the query string eg. set page to -1 and you get errors.

**Comment by jmayntzhusen** [comment]
Hey @DanDiplo 

Thanks for reporting this, I have taken the liberty of moving this issue to the package repo as that is where we concentrate our package related issues to have a better overview. 

Will add this to the list of Our improvements, and hopefully someone can pick this up soon 🙂

**Comment by jmayntzhusen** [comment]
Fixed by https://github.com/umbraco/OurUmbraco/pull/606
