### ISSUE TITLE
Ability to delete package files

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco.Packages#67]
# Feature request
Sometimes you may need to delete a package file rather than just archive it as maybe it contains code you don't want anyone to be using, or maybe your archive list is so long you wish to prune it of older releases no longer supported.

## Type of feature
Add an extra button in the "Current package files" table with a Delete button. It should probably have a confirmation dialog to ensure it's not deleted by mistake. Once deleted though, it shouldn't appear in any package file lists.

## Detailed description
Ability to permanently delete a package file.

**Comment by jmayntzhusen** [comment]
Depends on #68
