### ISSUE TITLE
Revamping the create / edit package pages

### ISSUE THREAD

**Issue by jmayntzhusen** [umbraco/Umbraco.Packages#68]
The current create / edit pages for packages on Our have a lot of bugs and bad UX. Before we start fixing the little things and extending functionality on the page we should change the underlying structure.

The first step is to consolidate the 4 pages into 1, use some client side code to make the UI more smooth and not submit every change as a form and potentially pre-filling some info based on an uploaded package file.

**Comment by skttl** [comment]
🎉
Maybe introduce some kind of API for automation while you are at it.

**Comment by jmayntzhusen** [comment]
What parts of the process would you like to have automated @skttl ? 🙂

**Comment by skttl** [comment]
Probably most of it, but at least setting the current version and upload a new package file.

But then you'll probably also want to be able to archive existing files, and maybe upload new screenshots. Hence "probably most of it" :)

**Comment by jmayntzhusen** [comment]
Ah yes, we have a few pending reviews, etc left but are very close to releasing a CLI tool for updating packages, can't currently do screenshots / archiving, etc. But can be done at a later point 🙂

You can see a quick gif of the workflow here: https://github.com/umbraco/OurUmbraco/pull/561#issuecomment-612066454

The tool works by talking to a new API on Our, that is not through review yet: https://github.com/umbraco/OurUmbraco/pull/552

You can check out the tool at the repo - and feel free to come with suggestions / issues and PRs 😊
https://github.com/umbraco/Umbraco-Packager-CLI
