### ISSUE TITLE
Getting rid of archived packages on Our

### ISSUE THREAD

**Issue by jmayntzhusen** [umbraco/Umbraco.Packages#69]
Had a thought and looking for some feedback 🙂

I'd like to get rid of archived packages on Our - or atleast remove it as something a package dev has to manage themselves, my idea is that we can do the following:

1. As suggested in https://github.com/umbraco/Umbraco.Packages/issues/67 - allow package owners to delete specific package files related to that package (would remove a lot of the need for archiving)
2. We have a specific api for the Umbraco backoffice to figure out which package file it needs to download based on the Umbraco version you are on, that API posts all versions you could potentially get, and which Umbraco versions they work for. We could use the same method to only show the packages that are current, and hide the other ones automatically as archived. Will also give package devs a better understanding of which packages are tied to which Umbraco versions.

Example of the returned data for fx UmbracoForms:
```json
0: {fileId: 20539, minUmbracoVersion: "8.0.0", packageVersion: "8.6.0"}
1: {fileId: 20541, minUmbracoVersion: "7.9.0", packageVersion: "7.15.0"}
2: {fileId: 18615, minUmbracoVersion: "7.6.0", packageVersion: "7.8.0"}
```

So we know which package version is the valid one for 
[7.6.0-7.9.0[
[7.9.0-8.0.0[
[8.0.0 -

Which are then the 3 files we could be showing, and also showing their Umbraco compatibility ranges. Of course this would mean any v4, v6 packages are hidden by default, and for package such as Forms where 3 files are uploaded for each release we would only show the "regular" zip file, not the other ones.

Any thoughts or ideas are very welcome 🙂

**Comment by mattbrailsford** [comment]
Would this be based on package name? So each unique package name + version range would remain current?

**Comment by jmayntzhusen** [comment]
Hmm good point, dont think it would work for fx your provider packages. How would you install those via the backoffice? (If you can at all)

**Comment by mattbrailsford** [comment]
You can't install them in the back office, other than manually, but yea, it's how do we leave multiple packages active if you are listing multiple packages at once.

Maybe we need some kind of dropdown on Our for the "Umbraco Version" and it displays current active packages that are available for that specific version? Always showing the latest unique packages with a supported version up to the given version number?

**Comment by jmayntzhusen** [comment]
Hmm it may be tough to automate this 🤔

If you released the providers as separate packages then it would work, that's also how it is in NuGet, but of course they then have dependency management to ensure you install dependent packages which we are missing 😬

Maybe archiving a regex match would be best in the end.. If you run it locally we could return a list of matching packages that you'd need to confirm before it deploys, but not sure what we could do for CI/CD deployments..

**Comment by mattbrailsford** [comment]
The problem with releasing providers as individual packages is that there could be a lot so would require setting up many Our pages, and like you say there are of no use on their own so for me it made sense to just have them on the same package page.

I do think this could still work, but it is a tricky one for sure. I guess the main issue is that people have used it in many different ways so it's hard to capture all of them. Maybe this does then mean like you say, it would need to be in the hands of the developer to choose how this works via some regex pattern matching or the likes.
