### ISSUE TITLE
Use Markdown for package descriptions

### ISSUE THREAD

**Issue by abjerner** [umbraco/Umbraco.Packages#74]
When editing the description of a package, we currently have to use a simple version of the TinyMCE editor. In my experience, it's quite easy to get in a situation where the WYSIWYG preview looks different from when viewing the description on the actual package page.

The description of my new package contains a list between to paragraphs, but as can be seen from the screenshot below, there isn't any space between the list and the paragraph right after it.
![image](https://user-images.githubusercontent.com/3634580/89653316-250e3100-d8c7-11ea-891a-c664b7e3979e.png)

However the WYSIWYG editor shows the space just right, so it's a bit hard to get the description to look right. I always end up using a handful of attempts when having these issues. 

It's a bit of a hack, but you can change the HTML directly via dev tools in your browser, so I ended up inserting a `<br />` manually in the HTML:

![image](https://user-images.githubusercontent.com/3634580/89653287-145dbb00-d8c7-11ea-8ec8-32a5e20101cb.png)

Now there is too much space when seeing the description in the WYSIWYG editor, but it looks right on the package page:

![image](https://user-images.githubusercontent.com/3634580/89653210-fabc7380-d8c6-11ea-84ff-a6c4e372ac8a.png)

While trying to fix this, I also had some other issues with the WYSIWYG editor inserting empty paragraphs somewhat at random, causing extra space in places where it doesn't make sense. So even for a quite simple text, this ended up being quite annoying.

At least some of this can be fixed by proper styling. But this may also be the time to consider switching the format to Markdown instead of the WYSIWYG editor (or at least as an alternative). 

Our is already using Markdig for the documentation, so it could be used here for the package descriptions as well. It even allows more options for formatting the package description. We could even have code snippets in the description with syntax highlighting 😍 

So worth considering?

**Comment by jmayntzhusen** [comment]
Hey Anders,

Sorry for the slow response!

I think it is a great idea, something that has been mentioned a couple of times in our meetings as well!

As far as I know what needs to be done is the following:

- Set a convention for naming and placement of a markdown file in an Umbraco package zip (could be readme.md in the root fx)
- Edit the Our packageview to check for that file, run it through markdig and output the html - if it can't find the file it should fallback to the IPublishedContent description.

This was we don't require everyone to make the switch, but if you want to have more control / easier management you can "just" do it all in a markdown file 🙂

I will mark this as up for grabs for now, would love to get your feedback on my proposed solution, and if you want to take a crack at an Our pr then it's also great!

**Comment by skttl** [comment]
Perhaps a checkbox should be added to our, to determine if the readme.md file in the package should be used. I could suspect that some packages have such a file already, and don't want to have it replace the content on the package page.

**Comment by jmayntzhusen** [comment]
Good call Søren! I'd prefer to not have too much config needed on Our as it's already quite messy, would much rather have it based on conventions we could document. You have here a very good reason to not call it `readme.md`, could instead call it something like `description.md` or `package-description.md` to ensure it won't conflict with what package authors currently include.

Down the line this could also be adapted in the backoffice so we could get rid of the CData description element in the package.xml 🤞 - but let's see where we end up with that format 😉

My suggested approach above was mostly a non-breaking change that allows for more flexibility and is quite easy to do right now 😊

**Comment by abjerner** [comment]
I was actually thinking about when editing the project/package description directly from Our. I don't see this directly linked with the description of the package file, but perhaps something like @skttl describes with an opt-in (or opt-out) could be a thing.

**Comment by jmayntzhusen** [comment]
Hmm my assumptions were way off then 🤔

I was thinking if the description comes from a md file inside the package you would not have to ever really edit the package on Our, you could do things like adding a changelog way easier if you had the md file in your package repo and used UmbPack to pack and update the file on Our..

So what you meant originally @abjerner was more to the effect of the current wysiwyg editor being bad to work with, and replacing it with a better one, or a markdown editor would make it easier to format the description?

**Comment by abjerner** [comment]
> So what you meant originally @abjerner was more to the effect of the current wysiwyg editor being bad to work with, and replacing it with a better one, or a markdown editor would make it easier to format the description?

Yes 😍 

Personally I don't really pay much attention to the description inside the package. But then again, I also prefer to install packages via NuGet 🤔
