### ISSUE TITLE
Article(s): Utilizing backoffice functionality

### ISSUE THREAD

**Issue by jmayntzhusen** [umbraco/Umbraco.Packages#8]
May need to split this into more dependent on what we believe is best, but an initial list of ideas is this:

- [ ] Storing data using migrations
- [ ] Common backoffice UI components to use
- [ ] Utilizing Angular services / resources
- [ ] Using infinite editing - https://github.com/umbraco/UmbracoDocs/issues/2045
- [ ] Storing configuration - https://github.com/umbraco/Umbraco-CMS/issues/3911

**Comment by dawoe** [comment]
For some of these there is already documentation ;
Migrations : https://our.umbraco.com/documentation/Extending/Database/
Tours : https://our.umbraco.com/documentation/Extending/Backoffice-Tours/

Maybe we can extend the migrations documentation with some of the information Stephan blogged about a while ago.
https://www.zpqrtbnk.net/posts/migrations-in-v8/
https://www.zpqrtbnk.net/posts/migrations-in-v8-2/

**Comment by jmayntzhusen** [comment]
I think we may want something around migrations specifically for package uses - things like considerations around versioning, installing and uninstalling, etc?

I think infinite editing may not need anything around packages - unless there are some package specific considerations I don't know about.. It just currently doesn't have any documentation on how to implement it at all, which was why I added it.

**Comment by jmayntzhusen** [comment]
I will close this issue as it is not specific enough 🙂 New issues for each of these things will be added!
