### ISSUE TITLE
Show all downloads on Our

### ISSUE THREAD

**Issue by jmayntzhusen** [umbraco/Umbraco.Packages#9]
The downloads on Our are from the package repository only, doesn't include Nuget package downloads:
![image](https://user-images.githubusercontent.com/36075913/67958123-e8eec700-fbf6-11e9-8800-4209a305ea47.png)

However as you see on the top there, we know the Nuget alias of the package, and based on the alias you can call this API: 
```https://api-v2v3search-0.nuget.org/query?q=packageid:Our.Umbraco.SuperValueConverters```

Which will give the total amount of downloads as well. Would be cool to add the numbers together 🙂
 
![image](https://user-images.githubusercontent.com/36075913/67958378-6286b500-fbf7-11e9-91bc-ebe2c2e5115c.png)

In the specific case of SuperValueConverters it would bump the downloads up from around 200 to around 1400, quite a significant difference!

**Comment by dawoe** [comment]
Yeah.. would be nice to integrate. But maybe not realtime for the sake of performance. I know there is already a scheduled import from github which is stored in a custom examine index. We could go the same route.

Dave

**Comment by dawoe** [comment]
Hi all,

I have made a start on this one. Probably will work some more on it during the UK Festival hackaton

Dave

**Comment by jmayntzhusen** [comment]
Has been merged in so will close 🙂
